[project]
authors = ["David Fullmer <david.d.fullmer@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "MSR"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.2.5,<5"
jinja2 = ">=3.1.4,<4"
reportlab = ">=4.2.5,<5"
